Exercise 2 - Filters/CarDealerApp/CarDealerApp/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CarDealer.Data;
using CarDealer.Models.BindingModels;
using CarDealer.Models.EntityModels;
using CarDealer.Services;
using Microsoft.Ajax.Utilities;

namespace CarDealerApp.Controllers
{
    public class CustomersController : Controller
    {
        private CarDealerContext db = new CarDealerContext();
        private CustomerService service = new CustomerService(Data.Context);

        // GET: Customers

        [Route("~/customers/all")]
        public ActionResult Index()
        {
            IEnumerable<Customer> customers = this.db.Customers.ToList();
            return View(customers);
        }

        [Route("~/customers/all/{sorthType}")]
        public ActionResult Index(string sorthType)
        {
            IEnumerable<Customer> orderedCustomers = null;

            if (sorthType == "ascending")
            {
                orderedCustomers = this.db.Customers.OrderBy(c => c.BirthDate).ThenBy(c => c.IsYoungDriver);
            }

            else if (sorthType == "descending")
            {
                orderedCustomers = this.db.Customers.OrderByDescending(c => c.BirthDate).ThenBy(c => c.IsYoungDriver);
            }

            else
            {
                orderedCustomers = this.db.Customers;
            }

            return View(orderedCustomers.ToList());
        }

        [Route("~/customers")]
        public ActionResult TotalSales()
        {
            Customer customer = this.db.Customers.Find(1);
            return View(customer);
        }

        [Route("~/customers/{id:int}")]
        public ActionResult TotalSales(int id)
        {
            Customer customer = this.db.Customers.Find(id);
            return View(customer);
        }

        // GET: Customers/Create
        [Route("~/Customers/Add")]
        public ActionResult Add()
        {
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Route("~/Customers/Add")]
        public ActionResult Add([Bind(Include = "Name,BirthDate")] AddCustomerBindingModel addCustomerBindingModel)
        {
            if (this.ModelState.IsValid)
            {
                this.service.AddCustomer(addCustomerBindingModel);
                return this.RedirectToAction("Index");
            }

            return this.View();
        }

        [Route("~/Customers/Edit")]
        public ActionResult Edit()
        {
            EditCustomerBindingModel bind = this.service.GetEditedCustomer();
            return this.View(bind);
        }

        [Route("~/Customers/Edit/{id:int}")]
        public ActionResult Edit(int id)
        {
            EditCustomerBindingModel bind = this.service.GetEditedCustomer(id);
            return this.View(bind);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Route("~/Customers/Edit/{id:int}")]
        public ActionResult Edit([Bind(Include = "Id,Name,BirthDate")] EditCustomerBindingModel bind)
        {
            if (this.ModelState.IsValid)
            {
                this.service.EditCustomer(bind);
                return this.RedirectToAction("Index");
            }

            return this.View();
        }

        [Route("~/Customers/Delete")]
        public ActionResult Delete()
        {
            this.service.DeleteCustomer();
            return this.RedirectToAction("Index");
        }

        [Route("~/Customers/Delete/{id:int}")]
        public ActionResult Delete(int id)
        {
            this.service.DeleteCustomer(id);
            return this.RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Exercise 2 - Filters/CarDealerApp/CarDealerApp/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CarDealer.Data;
using CarDealer.Models.BindingModels;
using CarDealer.Models.EntityModels;
using CarDealer.Services;
using CarDealerApp.Security;
using AuthenticationManager = CarDealerApp.Security.AuthenticationManager;

namespace CarDealerApp.Controllers
{
    public class UsersController : Controller
    {
        private CarDealerContext db = new CarDealerContext();
        private UsersService service = new UsersService(Data.Context);

        [Route("~/users/register")]
        public ActionResult Register()
        {
            return this.View();
        }

        [HttpPost]
        [Route("~/users/register")]
        public ActionResult Register([Bind(Include = "Username, Email, Password, ConfirmPassword")] RegisterUserBindingModel bindingModel)
        {
            if (this.ModelState.IsValid)
            {
                this.service.RegisterUser(bindingModel);
                return this.Redirect("~/home/index");
            }

            return this.View();
        }

        [Route("~/users/login")]
        public ActionResult Login()
        {
            return this.View();
        }

        [HttpPost]
        [Route("~/users/login")]
        public ActionResult Login([Bind(Include = "Username, Password")] LoginUserBindingModel bindingModel)
        {
            var httpCoockie = this.Request.Cookies.Get("sessionId");

            if (httpCoockie != null && AuthenticationManager.IsAuthenticated(httpCoockie.Value))
            {
                return this.RedirectToAction("Index", "Cars");
            }

            if (this.ModelState.IsValid && this.service.UserExists(bindingModel))
            {
                this.service.LoginUser(bindingModel, this.Session.SessionID);
                this.Response.SetCookie(new HttpCookie("sessionId", this.Session.SessionID));
                return this.RedirectToAction("Index", "Cars");
            }

            return this.View();
        }

        [Route("~/users/logout")]
        public ActionResult Logout()
        {
            var httpCoockie = this.Request.Cookies.Get("sessionId");

            if (httpCoockie == null || !AuthenticationManager.IsAuthenticated(httpCoockie.Value))
            {
                return this.RedirectToAction("Login");
            }

            AuthenticationManager.Logout(this.Request.Cookies.Get("sessionId").Value);
            return this.RedirectToAction("Index", "Cars");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Exercise 2 - Filters/CarDealerApp/CarDealerApp/Views/Shared/InvalidOperationError.cshtml
@model HandleErrorInfo

@{
    ViewBag.Title = "InvalidOperationError";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    h1 {
        text-align: center;
    }
</style>

<h1 class="text-danger">Sorry, an error occured while proccessing your request.</h1>
<br />
<h2>Error: @Model.Exception.Message</h2>

Exercise 2 - Filters/CarDealerApp/CarDealerApp/Views/Shared/OutOfRangeError.cshtml
@model HandleErrorInfo

@{
    ViewBag.Title = "OutOfRangeError";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    h1 {
        text-align: center;
        text-transform: uppercase;
    }

    img {
        margin-left: 540px;
    }
</style>

<h1 class="text-danger">Sorry, an error occured.</h1>
<br/>
<h2>Range Error: @Model.Exception.Message</h2>

<img src="http://www.clipartkid.com/images/452/clipartbest-com-uyhmfp-clipart.png" alt="Sad face" width="100" />

Exercise 2 - Filters/CarDealerApp/CarDealerApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Car Dealer</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Car Dealer", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Customers
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("All", "Index", "Customers", new { sortType = "all" }, null)</li>
                            <li>@Html.ActionLink("Ascending", "Index", "Customers", new { sortType = "ascending" }, null)</li>
                            <li>@Html.ActionLink("Descending", "Index", "Customers", new { sortType = "descending" }, null)</li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Cars", "Index", "Cars")</li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Suppliers
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("All", "Index", "Suppliers")</li>
                            <li>@Html.ActionLink("Local", "Index", "Suppliers", new {type = "local"}, null)</li>
                            <li>@Html.ActionLink("Importers", "Index", "Suppliers", new {type = "importer"}, null)</li>
                            <li>@Html.ActionLink("Add", "Add", "Suppliers")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Sales
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("All", "Index", "Sales")</li>
                            <li>@Html.ActionLink("Discounted", "Discounted", "Sales")</li>
                            <li>@Html.ActionLink("Add", "Add", "Sales")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Users
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Register", "Register", "Users")</li>
                            <li>@Html.ActionLink("Login", "Login", "Users")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Logs
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("All", "All", "Logs", new {page = 1}, null)</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Exercise 2 - Filters/CarDealerApp/CarDealerApp/Views/Shared/_Layout_LoggedUser.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Car Dealer</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Car Dealer", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Customers
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("All", "Index", "Customers", new { sortType = "all" }, null)</li>
                            <li>@Html.ActionLink("Ascending", "Index", "Customers", new { sortType = "ascending" }, null)</li>
                            <li>@Html.ActionLink("Descending", "Index", "Customers", new { sortType = "descending" }, null)</li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Cars", "Index", "Cars")</li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Suppliers
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("All", "Index", "Suppliers")</li>
                            <li>@Html.ActionLink("Local", "Index", "Suppliers", new {type = "local"}, null)</li>
                            <li>@Html.ActionLink("Importers", "Index", "Suppliers", new {type = "importer"}, null)</li>
                            <li>@Html.ActionLink("Add", "Add", "Suppliers")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Sales
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("All", "Index", "Sales")</li>
                            <li>@Html.ActionLink("Discounted", "Discounted", "Sales")</li>
                            <li>@Html.ActionLink("Add", "Add", "Sales")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Users
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Logout", "Logout", "Users")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Logs
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("All", "All", "Logs", new { page = 1 }, null)</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>